//! Auto-generated from sktmorph/sarvanama.py
use std::collections::HashMap;
use serde::{Deserialize, Serialize};
#[derive(Serialize, Deserialize, Debug)] pub struct PronounTable { pub base: String, pub linga: String, pub table: HashMap<String, Vec<String>> }
fn pronouns() -> HashMap<(String,String), Vec<Vec<String>>> { let mut m=HashMap::new();
  m.insert(("tad".to_string(),"pum".to_string()), vec![vec!["saH".to_string(),"tO".to_string(),"te".to_string(),],vec!["tam".to_string(),"tO".to_string(),"tAn".to_string(),],vec!["tena".to_string(),"tAByAm".to_string(),"tEH".to_string(),],vec!["tasmE".to_string(),"tAByAm".to_string(),"teByaH".to_string(),],vec!["tasmAt".to_string(),"tAByAm".to_string(),"teByaH".to_string(),],vec!["tasya".to_string(),"tayoH".to_string(),"tezAm".to_string(),],vec!["tasmin".to_string(),"tayoH".to_string(),"tezu".to_string(),],]);
  m.insert(("tad".to_string(),"stri".to_string()), vec![vec!["sA".to_string(),"te".to_string(),"tAH".to_string(),],vec!["tAm".to_string(),"te".to_string(),"tAH".to_string(),],vec!["tayA".to_string(),"tAByAm".to_string(),"tABiH".to_string(),],vec!["tasyE".to_string(),"tAByAm".to_string(),"tAByaH".to_string(),],vec!["tasyAH".to_string(),"tAByAm".to_string(),"tAByaH".to_string(),],vec!["tasyAH".to_string(),"tayoH".to_string(),"tAsAm".to_string(),],vec!["tasyAm".to_string(),"tayoH".to_string(),"tAzu".to_string(),],]);
  m.insert(("tad".to_string(),"nap".to_string()), vec![vec!["tat".to_string(),"te".to_string(),"tAni".to_string(),],vec!["tat".to_string(),"te".to_string(),"tAni".to_string(),],vec!["tena".to_string(),"tAByAm".to_string(),"tEH".to_string(),],vec!["tasmE".to_string(),"tAByAm".to_string(),"teByaH".to_string(),],vec!["tasmAt".to_string(),"tAByAm".to_string(),"teByaH".to_string(),],vec!["tasya".to_string(),"tayoH".to_string(),"tezAm".to_string(),],vec!["tasmin".to_string(),"tayoH".to_string(),"tezu".to_string(),],]);
  m.insert(("kim".to_string(),"pum".to_string()), vec![vec!["kaH".to_string(),"kO".to_string(),"ke".to_string(),],vec!["kam".to_string(),"kO".to_string(),"kAn".to_string(),],vec!["kena".to_string(),"kAByAm".to_string(),"kEH".to_string(),],vec!["kasmE".to_string(),"kAByAm".to_string(),"keByaH".to_string(),],vec!["kasmAt".to_string(),"kAByAm".to_string(),"keByaH".to_string(),],vec!["kasya".to_string(),"kayoH".to_string(),"kezAm".to_string(),],vec!["kasmin".to_string(),"kayoH".to_string(),"kezu".to_string(),],]);
  m.insert(("kim".to_string(),"stri".to_string()), vec![vec!["kA".to_string(),"ke".to_string(),"kAH".to_string(),],vec!["kAm".to_string(),"ke".to_string(),"kAH".to_string(),],vec!["kayA".to_string(),"kAByAm".to_string(),"kABiH".to_string(),],vec!["kasyE".to_string(),"kAByAm".to_string(),"kAByaH".to_string(),],vec!["kasyAH".to_string(),"kAByAm".to_string(),"kAByaH".to_string(),],vec!["kasyAH".to_string(),"kayoH".to_string(),"kAsAm".to_string(),],vec!["kasyAm".to_string(),"kayoH".to_string(),"kAzu".to_string(),],]);
  m.insert(("kim".to_string(),"nap".to_string()), vec![vec!["kim".to_string(),"ke".to_string(),"kAni".to_string(),],vec!["kim".to_string(),"ke".to_string(),"kAni".to_string(),],vec!["kena".to_string(),"kAByAm".to_string(),"kEH".to_string(),],vec!["kasmE".to_string(),"kAByAm".to_string(),"keByaH".to_string(),],vec!["kasmAt".to_string(),"kAByAm".to_string(),"keByaH".to_string(),],vec!["kasya".to_string(),"kayoH".to_string(),"kezAm".to_string(),],vec!["kasmin".to_string(),"kayoH".to_string(),"kezu".to_string(),],]);
  m.insert(("asmad".to_string(),"any".to_string()), vec![vec!["aham".to_string(),"AvAm".to_string(),"vayam".to_string(),],vec!["mAm,mA".to_string(),"AvAm,nO".to_string(),"asmAn,naH".to_string(),],vec!["mayA".to_string(),"AvAByAm".to_string(),"asmABiH".to_string(),],vec!["mahyam,me".to_string(),"AvAByAm,nO".to_string(),"asmaByam,naH".to_string(),],vec!["mat".to_string(),"AvAByAm".to_string(),"asmat".to_string(),],vec!["mama,me".to_string(),"AvayoH,nO".to_string(),"asmAkam,naH".to_string(),],vec!["mayi".to_string(),"AvayoH".to_string(),"asmAsu".to_string(),],]);
  m.insert(("yuzmad".to_string(),"any".to_string()), vec![vec!["tvam".to_string(),"yuvAm".to_string(),"yUyam".to_string(),],vec!["tvAm,tvA".to_string(),"yuvAm,vAm".to_string(),"yuzmAn,vaH".to_string(),],vec!["tvayA".to_string(),"yuvAByAm".to_string(),"yuzmABiH".to_string(),],vec!["tuByam,te".to_string(),"yuvAByAm,vAm".to_string(),"yuzmaByam,vaH".to_string(),],vec!["tvat".to_string(),"yuvAByAm".to_string(),"yuzmat".to_string(),],vec!["tava,te".to_string(),"yuvayoH,vAm".to_string(),"yuzmAkam,vaH".to_string(),],vec!["tvayi".to_string(),"yuvayoH".to_string(),"yuzmAsu".to_string(),],]);
  m.insert(("sarva".to_string(),"pum".to_string()), vec![vec!["sarvaH".to_string(),"sarvO".to_string(),"sarve".to_string(),],vec!["sarvam".to_string(),"sarvO".to_string(),"sarvAn".to_string(),],vec!["sarveRa".to_string(),"sarvAByAm".to_string(),"sarvEH".to_string(),],vec!["sarvasmE".to_string(),"sarvAByAm".to_string(),"sarveByaH".to_string(),],vec!["sarvasmAt".to_string(),"sarvAByAm".to_string(),"sarveByaH".to_string(),],vec!["sarvasya".to_string(),"sarvayoH".to_string(),"sarvezAm".to_string(),],vec!["sarvasmin".to_string(),"sarvayoH".to_string(),"sarvezu".to_string(),],vec!["sarva".to_string(),"sarvO".to_string(),"sarve".to_string(),],]);
  m.insert(("sarva".to_string(),"stri".to_string()), vec![vec!["sarvA".to_string(),"sarve".to_string(),"sarvAH".to_string(),],vec!["sarvAm".to_string(),"sarve".to_string(),"sarvAH".to_string(),],vec!["sarvayA".to_string(),"sarvAByAm".to_string(),"sarvABiH".to_string(),],vec!["sarvasyE".to_string(),"sarvAByAm".to_string(),"sarvAByaH".to_string(),],vec!["sarvasyAH".to_string(),"sarvAByAm".to_string(),"sarvAByaH".to_string(),],vec!["sarvasyAH".to_string(),"sarvayoH".to_string(),"sarvAsAm".to_string(),],vec!["sarvasyAm".to_string(),"sarvayoH".to_string(),"sarvAzu".to_string(),],vec!["sarve".to_string(),"sarve".to_string(),"sarvAH".to_string(),],]);
  m.insert(("sarva".to_string(),"nap".to_string()), vec![vec!["sarvam".to_string(),"sarve".to_string(),"sarvARi".to_string(),],vec!["sarvam".to_string(),"sarve".to_string(),"sarvARi".to_string(),],vec!["sarveRa".to_string(),"sarvAByAm".to_string(),"sarvEH".to_string(),],vec!["sarvasmE".to_string(),"sarvAByAm".to_string(),"sarveByaH".to_string(),],vec!["sarvasmAt".to_string(),"sarvAByAm".to_string(),"sarveByaH".to_string(),],vec!["sarvasya".to_string(),"sarvayoH".to_string(),"sarvezAm".to_string(),],vec!["sarvasmin".to_string(),"sarvayoH".to_string(),"sarvezu".to_string(),],vec!["sarva".to_string(),"sarve".to_string(),"sarvARi".to_string(),],]);
  m.insert(("idam".to_string(),"pum".to_string()), vec![vec!["ayam".to_string(),"imO".to_string(),"ime".to_string(),],vec!["enam".to_string(),"imO".to_string(),"imAn".to_string(),],vec!["enena".to_string(),"AByAm".to_string(),"EBiH".to_string(),],vec!["asmai".to_string(),"AByAm".to_string(),"EByaH".to_string(),],vec!["asmAt".to_string(),"AByAm".to_string(),"EByaH".to_string(),],vec!["asya".to_string(),"imoH".to_string(),"ezAm".to_string(),],vec!["asmin".to_string(),"imoH".to_string(),"ezu".to_string(),],]);
  m.insert(("idam".to_string(),"stri".to_string()), vec![vec!["iyam".to_string(),"ime".to_string(),"imAH".to_string(),],vec!["imAm".to_string(),"ime".to_string(),"imAH".to_string(),],vec!["ayA".to_string(),"AByAm".to_string(),"ABiH".to_string(),],vec!["asyE".to_string(),"AByAm".to_string(),"AByaH".to_string(),],vec!["asyAH".to_string(),"AByAm".to_string(),"AByaH".to_string(),],vec!["asyAH".to_string(),"imoH".to_string(),"imAm".to_string(),],vec!["asyAm".to_string(),"imoH".to_string(),"imAsu".to_string(),],]);
  m.insert(("idam".to_string(),"nap".to_string()), vec![vec!["idam".to_string(),"ime".to_string(),"imAni".to_string(),],vec!["idam".to_string(),"ime".to_string(),"imAni".to_string(),],vec!["enena".to_string(),"AByAm".to_string(),"EBiH".to_string(),],vec!["asmai".to_string(),"AByAm".to_string(),"EByaH".to_string(),],vec!["asmAt".to_string(),"AByAm".to_string(),"EByaH".to_string(),],vec!["asya".to_string(),"imoH".to_string(),"ezAm".to_string(),],vec!["asmin".to_string(),"imoH".to_string(),"ezu".to_string(),],]);
  m.insert(("etad".to_string(),"pum".to_string()), vec![vec!["ezaH".to_string(),"etO".to_string(),"ete".to_string(),],vec!["etam".to_string(),"etO".to_string(),"etAn".to_string(),],vec!["etena".to_string(),"etAByAm".to_string(),"etEBiH".to_string(),],vec!["etasmE".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasmAt".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasya".to_string(),"etayoH".to_string(),"etezAm".to_string(),],vec!["etasmin".to_string(),"etayoH".to_string(),"etezu".to_string(),],]);
  m.insert(("etad".to_string(),"stri".to_string()), vec![vec!["etA".to_string(),"ete".to_string(),"etAH".to_string(),],vec!["etAm".to_string(),"ete".to_string(),"etAH".to_string(),],vec!["etayA".to_string(),"etAByAm".to_string(),"etABiH".to_string(),],vec!["etasyE".to_string(),"etAByAm".to_string(),"etAByaH".to_string(),],vec!["etasyAH".to_string(),"etAByAm".to_string(),"etAByaH".to_string(),],vec!["etasyAH".to_string(),"etayoH".to_string(),"etAsAm".to_string(),],vec!["etasyAm".to_string(),"etayoH".to_string(),"etAsu".to_string(),],]);
  m.insert(("etad".to_string(),"nap".to_string()), vec![vec!["etat".to_string(),"ete".to_string(),"etAni".to_string(),],vec!["etat".to_string(),"ete".to_string(),"etAni".to_string(),],vec!["etena".to_string(),"etAByAm".to_string(),"etEBiH".to_string(),],vec!["etasmE".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasmAt".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasya".to_string(),"etayoH".to_string(),"etezAm".to_string(),],vec!["etasmin".to_string(),"etayoH".to_string(),"etezu".to_string(),],]);
  m.insert(("yad".to_string(),"pum".to_string()), vec![vec!["yaH".to_string(),"yO".to_string(),"ye".to_string(),],vec!["yam".to_string(),"yO".to_string(),"yAn".to_string(),],vec!["yena".to_string(),"yAByAm".to_string(),"yEH".to_string(),],vec!["yasmE".to_string(),"yAByAm".to_string(),"yeByaH".to_string(),],vec!["yasmAt".to_string(),"yAByAm".to_string(),"yeByaH".to_string(),],vec!["yasya".to_string(),"yayoH".to_string(),"yezAm".to_string(),],vec!["yasmin".to_string(),"yayoH".to_string(),"yezu".to_string(),],]);
  m.insert(("yad".to_string(),"stri".to_string()), vec![vec!["yA".to_string(),"ye".to_string(),"yAH".to_string(),],vec!["yAm".to_string(),"ye".to_string(),"yAH".to_string(),],vec!["yayA".to_string(),"yAByAm".to_string(),"yABiH".to_string(),],vec!["yasyE".to_string(),"yAByAm".to_string(),"yAByaH".to_string(),],vec!["yasyAH".to_string(),"yAByAm".to_string(),"yAByaH".to_string(),],vec!["yasyAH".to_string(),"yayoH".to_string(),"yAsAm".to_string(),],vec!["yasyAm".to_string(),"yayoH".to_string(),"yAsu".to_string(),],]);
  m.insert(("yad".to_string(),"nap".to_string()), vec![vec!["yat".to_string(),"ye".to_string(),"yAni".to_string(),],vec!["yat".to_string(),"ye".to_string(),"yAni".to_string(),],vec!["yena".to_string(),"yAByAm".to_string(),"yEH".to_string(),],vec!["yasmE".to_string(),"yAByAm".to_string(),"yeByaH".to_string(),],vec!["yasmAt".to_string(),"yAByAm".to_string(),"yeByaH".to_string(),],vec!["yasya".to_string(),"yayoH".to_string(),"yezAm".to_string(),],vec!["yasmin".to_string(),"yayoH".to_string(),"yezu".to_string(),],]);
  m.insert(("ubha".to_string(),"any".to_string()), vec![vec!["ubhau".to_string(),"ubhau".to_string(),"ubhe".to_string(),],vec!["ubhau".to_string(),"ubhau".to_string(),"ubhe".to_string(),],vec!["ubhABhyAm".to_string(),"ubhABhyAm".to_string(),"ubhABhiH".to_string(),],vec!["ubhABhyAm".to_string(),"ubhABhyAm".to_string(),"ubhABhyaH".to_string(),],vec!["ubhABhyAm".to_string(),"ubhABhyAm".to_string(),"ubhABhyaH".to_string(),],vec!["ubhayoH".to_string(),"ubhayoH".to_string(),"ubhAm".to_string(),],vec!["ubhayoH".to_string(),"ubhayoH".to_string(),"ubhAsu".to_string(),],]);
  m.insert(("ena".to_string(),"pum".to_string()), vec![vec!["ezaH".to_string(),"etO".to_string(),"ete".to_string(),],vec!["etam".to_string(),"etO".to_string(),"etAn".to_string(),],vec!["etena".to_string(),"etAByAm".to_string(),"etEBiH".to_string(),],vec!["etasmE".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasmAt".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasya".to_string(),"etayoH".to_string(),"etezAm".to_string(),],vec!["etasmin".to_string(),"etayoH".to_string(),"etezu".to_string(),],]);
  m.insert(("ena".to_string(),"stri".to_string()), vec![vec!["etA".to_string(),"ete".to_string(),"etAH".to_string(),],vec!["etAm".to_string(),"ete".to_string(),"etAH".to_string(),],vec!["etayA".to_string(),"etAByAm".to_string(),"etABiH".to_string(),],vec!["etasyE".to_string(),"etAByAm".to_string(),"etAByaH".to_string(),],vec!["etasyAH".to_string(),"etAByAm".to_string(),"etAByaH".to_string(),],vec!["etasyAH".to_string(),"etayoH".to_string(),"etAsAm".to_string(),],vec!["etasyAm".to_string(),"etayoH".to_string(),"etAsu".to_string(),],]);
  m.insert(("ena".to_string(),"nap".to_string()), vec![vec!["etat".to_string(),"ete".to_string(),"etAni".to_string(),],vec!["etat".to_string(),"ete".to_string(),"etAni".to_string(),],vec!["etena".to_string(),"etAByAm".to_string(),"etEBiH".to_string(),],vec!["etasmE".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasmAt".to_string(),"etAByAm".to_string(),"eteByaH".to_string(),],vec!["etasya".to_string(),"etayoH".to_string(),"etezAm".to_string(),],vec!["etasmin".to_string(),"etayoH".to_string(),"etezu".to_string(),],]);
  m.insert(("eka".to_string(),"pum".to_string()), vec![vec!["ekaH".to_string(),"ekO".to_string(),"eke".to_string(),],vec!["ekam".to_string(),"ekO".to_string(),"ekAn".to_string(),],vec!["ekena".to_string(),"ekAByAm".to_string(),"ekEBiH".to_string(),],vec!["ekasmE".to_string(),"ekAByAm".to_string(),"ekeByaH".to_string(),],vec!["ekasmAt".to_string(),"ekAByAm".to_string(),"ekeByaH".to_string(),],vec!["ekasya".to_string(),"ekayoH".to_string(),"ekezAm".to_string(),],vec!["ekasmin".to_string(),"ekayoH".to_string(),"ekezu".to_string(),],]);
  m.insert(("eka".to_string(),"stri".to_string()), vec![vec!["ekA".to_string(),"eke".to_string(),"ekAH".to_string(),],vec!["ekAm".to_string(),"eke".to_string(),"ekAH".to_string(),],vec!["ekayA".to_string(),"ekAByAm".to_string(),"ekABiH".to_string(),],vec!["ekasyE".to_string(),"ekAByAm".to_string(),"ekAByaH".to_string(),],vec!["ekasyAH".to_string(),"ekAByAm".to_string(),"ekAByaH".to_string(),],vec!["ekasyAH".to_string(),"ekayoH".to_string(),"ekAsAm".to_string(),],vec!["ekasyAm".to_string(),"ekayoH".to_string(),"ekAsu".to_string(),],]);
  m.insert(("eka".to_string(),"nap".to_string()), vec![vec!["ekam".to_string(),"eke".to_string(),"ekAni".to_string(),],vec!["ekam".to_string(),"eke".to_string(),"ekAni".to_string(),],vec!["ekena".to_string(),"ekAByAm".to_string(),"ekEBiH".to_string(),],vec!["ekasmE".to_string(),"ekAByAm".to_string(),"ekeByaH".to_string(),],vec!["ekasmAt".to_string(),"ekAByAm".to_string(),"ekeByaH".to_string(),],vec!["ekasya".to_string(),"ekayoH".to_string(),"ekezAm".to_string(),],vec!["ekasmin".to_string(),"ekayoH".to_string(),"ekezu".to_string(),],]);
  m.insert(("dvi".to_string(),"pum".to_string()), vec![vec!["dviH".to_string(),"dvO".to_string(),"dve".to_string(),],vec!["dvim".to_string(),"dvO".to_string(),"dvIn".to_string(),],vec!["dviByA".to_string(),"dviByAm".to_string(),"dviBiH".to_string(),],vec!["dviByE".to_string(),"dviByAm".to_string(),"dviByaH".to_string(),],vec!["dviByaH".to_string(),"dviByAm".to_string(),"dviByaH".to_string(),],vec!["dviByaH".to_string(),"dviByoH".to_string(),"dviByAm".to_string(),],vec!["dviByi".to_string(),"dviByoH".to_string(),"dviByasu".to_string(),],]);
  m.insert(("dvi".to_string(),"stri".to_string()), vec![vec!["dviH".to_string(),"dve".to_string(),"dviH".to_string(),],vec!["dviHm".to_string(),"dve".to_string(),"dviH".to_string(),],vec!["dviByA".to_string(),"dviByAm".to_string(),"dviBiH".to_string(),],vec!["dviByE".to_string(),"dviByAm".to_string(),"dviByaH".to_string(),],vec!["dviByaH".to_string(),"dviByAm".to_string(),"dviByaH".to_string(),],vec!["dviByaH".to_string(),"dviByoH".to_string(),"dviByAm".to_string(),],vec!["dviByi".to_string(),"dviByoH".to_string(),"dviByasu".to_string(),],]);
  m.insert(("dvi".to_string(),"nap".to_string()), vec![vec!["dvi".to_string(),"dvi".to_string(),"dvi".to_string(),],vec!["dvi".to_string(),"dvi".to_string(),"dvi".to_string(),],vec!["dviByA".to_string(),"dviByAm".to_string(),"dviBiH".to_string(),],vec!["dviByE".to_string(),"dviByAm".to_string(),"dviByaH".to_string(),],vec!["dviByaH".to_string(),"dviByAm".to_string(),"dviByaH".to_string(),],vec!["dviByaH".to_string(),"dviByoH".to_string(),"dviByAm".to_string(),],vec!["dviByi".to_string(),"dviByoH".to_string(),"dviByasu".to_string(),],]);
  m.insert(("sva".to_string(),"pum".to_string()), vec![vec!["svaH".to_string(),"svO".to_string(),"sve".to_string(),],vec!["svam".to_string(),"svO".to_string(),"svAn".to_string(),],vec!["svena".to_string(),"svAByAm".to_string(),"svEBiH".to_string(),],vec!["svasmE".to_string(),"svAByAm".to_string(),"sveByaH".to_string(),],vec!["svasmAt".to_string(),"svAByAm".to_string(),"sveByaH".to_string(),],vec!["svasya".to_string(),"svayoH".to_string(),"svezAm".to_string(),],vec!["svasmin".to_string(),"svayoH".to_string(),"svezu".to_string(),],]);
  m.insert(("sva".to_string(),"stri".to_string()), vec![vec!["svA".to_string(),"sve".to_string(),"svAH".to_string(),],vec!["svAm".to_string(),"sve".to_string(),"svAH".to_string(),],vec!["svayA".to_string(),"svAByAm".to_string(),"svABiH".to_string(),],vec!["svasyE".to_string(),"svAByAm".to_string(),"svAByaH".to_string(),],vec!["svasyAH".to_string(),"svAByAm".to_string(),"svAByaH".to_string(),],vec!["svasyAH".to_string(),"svayoH".to_string(),"svAsAm".to_string(),],vec!["svasyAm".to_string(),"svayoH".to_string(),"svAsu".to_string(),],]);
  m.insert(("sva".to_string(),"nap".to_string()), vec![vec!["svam".to_string(),"sve".to_string(),"svAni".to_string(),],vec!["svam".to_string(),"sve".to_string(),"svAni".to_string(),],vec!["svena".to_string(),"svAByAm".to_string(),"svEBiH".to_string(),],vec!["svasmE".to_string(),"svAByAm".to_string(),"sveByaH".to_string(),],vec!["svasmAt".to_string(),"svAByAm".to_string(),"sveByaH".to_string(),],vec!["svasya".to_string(),"svayoH".to_string(),"svezAm".to_string(),],vec!["svasmin".to_string(),"svayoH".to_string(),"svezu".to_string(),],]);
  m.insert(("am".to_string(),"any".to_string()), vec![vec!["am".to_string(),"am".to_string(),"am".to_string(),],vec!["am".to_string(),"am".to_string(),"am".to_string(),],vec!["am".to_string(),"am".to_string(),"am".to_string(),],vec!["am".to_string(),"am".to_string(),"am".to_string(),],vec!["am".to_string(),"am".to_string(),"am".to_string(),],vec!["am".to_string(),"am".to_string(),"am".to_string(),],vec!["am".to_string(),"am".to_string(),"am".to_string(),],]);
  m.insert(("traya".to_string(),"pum".to_string()), vec![vec!["trayaH".to_string(),"trayO".to_string(),"trayaH".to_string(),],vec!["trayam".to_string(),"trayO".to_string(),"trIn".to_string(),],vec!["tribhiH".to_string(),"tribhyAm".to_string(),"tribhiH".to_string(),],vec!["tribhyaH".to_string(),"tribhyAm".to_string(),"tribhyaH".to_string(),],vec!["tribhyaH".to_string(),"tribhyAm".to_string(),"tribhyaH".to_string(),],vec!["trayasya".to_string(),"trayoH".to_string(),"trayARAm".to_string(),],vec!["trizu".to_string(),"trizu".to_string(),"trizu".to_string(),],]);
  m.insert(("traya".to_string(),"stri".to_string()), vec![vec!["tisrA".to_string(),"tisro".to_string(),"tisraH".to_string(),],vec!["tisrAm".to_string(),"tisro".to_string(),"tisraH".to_string(),],vec!["tisrbhiH".to_string(),"tisrbhyAm".to_string(),"tisrbhiH".to_string(),],vec!["tisrbhyaH".to_string(),"tisrbhyAm".to_string(),"tisrbhyaH".to_string(),],vec!["tisrbhyaH".to_string(),"tisrbhyAm".to_string(),"tisrbhyaH".to_string(),],vec!["tisrasya".to_string(),"tisroH".to_string(),"tisrARAm".to_string(),],vec!["tisrizu".to_string(),"tisrizu".to_string(),"tisrizu".to_string(),],]);
  m.insert(("traya".to_string(),"nap".to_string()), vec![vec!["trayam".to_string(),"trIRi".to_string(),"trIRi".to_string(),],vec!["trayam".to_string(),"trIRi".to_string(),"trIRi".to_string(),],vec!["tribhiH".to_string(),"tribhyAm".to_string(),"tribhiH".to_string(),],vec!["tribhyaH".to_string(),"tribhyAm".to_string(),"tribhyaH".to_string(),],vec!["tribhyaH".to_string(),"tribhyAm".to_string(),"tribhyaH".to_string(),],vec!["trayasya".to_string(),"trayoH".to_string(),"trayARAm".to_string(),],vec!["trizu".to_string(),"trizu".to_string(),"trizu".to_string(),],]);
  m.insert(("catur".to_string(),"pum".to_string()), vec![vec!["catvAraH".to_string(),"catvArO".to_string(),"catvAraH".to_string(),],vec!["caturam".to_string(),"catvArO".to_string(),"catvARi".to_string(),],vec!["caturBiH".to_string(),"caturByAm".to_string(),"caturBiH".to_string(),],vec!["caturByaH".to_string(),"caturByAm".to_string(),"caturByaH".to_string(),],vec!["caturByaH".to_string(),"caturByAm".to_string(),"caturByaH".to_string(),],vec!["caturasya".to_string(),"caturNoH".to_string(),"caturARAm".to_string(),],vec!["caturzu".to_string(),"caturzu".to_string(),"caturzu".to_string(),],]);
  m.insert(("catur".to_string(),"stri".to_string()), vec![vec!["catasrA".to_string(),"catasro".to_string(),"catasraH".to_string(),],vec!["catasrAm".to_string(),"catasro".to_string(),"catasraH".to_string(),],vec!["catasrbhiH".to_string(),"catasrbhyAm".to_string(),"catasrbhiH".to_string(),],vec!["catasrbhyaH".to_string(),"catasrbhyAm".to_string(),"catasrbhyaH".to_string(),],vec!["catasrbhyaH".to_string(),"catasrbhyAm".to_string(),"catasrbhyaH".to_string(),],vec!["catasrasya".to_string(),"catasroH".to_string(),"catasrARAm".to_string(),],vec!["catasrizu".to_string(),"catasrizu".to_string(),"catasrizu".to_string(),],]);
  m.insert(("catur".to_string(),"nap".to_string()), vec![vec!["catur".to_string(),"catvArI".to_string(),"catvARi".to_string(),],vec!["catur".to_string(),"catvArI".to_string(),"catvARi".to_string(),],vec!["caturBiH".to_string(),"caturByAm".to_string(),"caturBiH".to_string(),],vec!["caturByaH".to_string(),"caturByAm".to_string(),"caturByaH".to_string(),],vec!["caturByaH".to_string(),"caturByAm".to_string(),"caturByaH".to_string(),],vec!["caturasya".to_string(),"caturNoH".to_string(),"caturARAm".to_string(),],vec!["caturzu".to_string(),"caturzu".to_string(),"caturzu".to_string(),],]);
  m.insert(("purva".to_string(),"pum".to_string()), vec![vec!["purvaH".to_string(),"purvO".to_string(),"purve".to_string(),],vec!["purvam".to_string(),"purvO".to_string(),"purvAn".to_string(),],vec!["purveRa".to_string(),"purvAByAm".to_string(),"purvEH".to_string(),],vec!["purvasmE".to_string(),"purvAByAm".to_string(),"purveByaH".to_string(),],vec!["purvasmAt".to_string(),"purvAByAm".to_string(),"purveByaH".to_string(),],vec!["purvasya".to_string(),"purvayoH".to_string(),"purvezAm".to_string(),],vec!["purvasmin".to_string(),"purvayoH".to_string(),"purvezu".to_string(),],vec!["purva".to_string(),"purvO".to_string(),"purve".to_string(),],]);
  m.insert(("purva".to_string(),"stri".to_string()), vec![vec!["purvA".to_string(),"purve".to_string(),"purvAH".to_string(),],vec!["purvAm".to_string(),"purve".to_string(),"purvAH".to_string(),],vec!["purvayA".to_string(),"purvAByAm".to_string(),"purvABiH".to_string(),],vec!["purvasyE".to_string(),"purvAByAm".to_string(),"purvAByaH".to_string(),],vec!["purvasyAH".to_string(),"purvAByAm".to_string(),"purvAByaH".to_string(),],vec!["purvasyAH".to_string(),"purvayoH".to_string(),"purvAsAm".to_string(),],vec!["purvasyAm".to_string(),"purvayoH".to_string(),"purvAzu".to_string(),],vec!["purve".to_string(),"purve".to_string(),"purvAH".to_string(),],]);
  m.insert(("purva".to_string(),"nap".to_string()), vec![vec!["purvam".to_string(),"purve".to_string(),"purvARi".to_string(),],vec!["purvam".to_string(),"purve".to_string(),"purvARi".to_string(),],vec!["purveRa".to_string(),"purvAByAm".to_string(),"purvEH".to_string(),],vec!["purvasmE".to_string(),"purvAByAm".to_string(),"purveByaH".to_string(),],vec!["purvasmAt".to_string(),"purvAByAm".to_string(),"purveByaH".to_string(),],vec!["purvasya".to_string(),"purvayoH".to_string(),"purvezAm".to_string(),],vec!["purvasmin".to_string(),"purvayoH".to_string(),"purvezu".to_string(),],vec!["purva".to_string(),"purve".to_string(),"purvARi".to_string(),],]);
  m.insert(("para".to_string(),"pum".to_string()), vec![vec!["paraH".to_string(),"parO".to_string(),"pare".to_string(),],vec!["param".to_string(),"parO".to_string(),"parAn".to_string(),],vec!["pareRa".to_string(),"parAByAm".to_string(),"parEH".to_string(),],vec!["parasmE".to_string(),"parAByAm".to_string(),"pareByaH".to_string(),],vec!["parasmAt".to_string(),"parAByAm".to_string(),"pareByaH".to_string(),],vec!["parasya".to_string(),"parayoH".to_string(),"parezAm".to_string(),],vec!["parasmin".to_string(),"parayoH".to_string(),"parezu".to_string(),],vec!["para".to_string(),"parO".to_string(),"pare".to_string(),],]);
  m.insert(("para".to_string(),"stri".to_string()), vec![vec!["parA".to_string(),"pare".to_string(),"parAH".to_string(),],vec!["parAm".to_string(),"pare".to_string(),"parAH".to_string(),],vec!["parayA".to_string(),"parAByAm".to_string(),"parABiH".to_string(),],vec!["parasyE".to_string(),"parAByAm".to_string(),"parAByaH".to_string(),],vec!["parasyAH".to_string(),"parAByAm".to_string(),"parAByaH".to_string(),],vec!["parasyAH".to_string(),"parayoH".to_string(),"parAsAm".to_string(),],vec!["parasyAm".to_string(),"parayoH".to_string(),"parAzu".to_string(),],vec!["pare".to_string(),"pare".to_string(),"parAH".to_string(),],]);
  m.insert(("para".to_string(),"nap".to_string()), vec![vec!["param".to_string(),"pare".to_string(),"parARi".to_string(),],vec!["param".to_string(),"pare".to_string(),"parARi".to_string(),],vec!["pareRa".to_string(),"parAByAm".to_string(),"parEH".to_string(),],vec!["parasmE".to_string(),"parAByAm".to_string(),"pareByaH".to_string(),],vec!["parasmAt".to_string(),"parAByAm".to_string(),"pareByaH".to_string(),],vec!["parasya".to_string(),"parayoH".to_string(),"parezAm".to_string(),],vec!["parasmin".to_string(),"parayoH".to_string(),"parezu".to_string(),],vec!["para".to_string(),"pare".to_string(),"parARi".to_string(),],]);
  m.insert(("apara".to_string(),"pum".to_string()), vec![vec!["aparaH".to_string(),"aparO".to_string(),"apare".to_string(),],vec!["aparam".to_string(),"aparO".to_string(),"aparAn".to_string(),],vec!["apareRa".to_string(),"aparAByAm".to_string(),"aparEH".to_string(),],vec!["aparasmE".to_string(),"aparAByAm".to_string(),"apareByaH".to_string(),],vec!["aparasmAt".to_string(),"aparAByAm".to_string(),"apareByaH".to_string(),],vec!["aparasya".to_string(),"aparayoH".to_string(),"aparezAm".to_string(),],vec!["aparasmin".to_string(),"aparayoH".to_string(),"aparezu".to_string(),],vec!["apara".to_string(),"aparO".to_string(),"apare".to_string(),],]);
  m.insert(("apara".to_string(),"stri".to_string()), vec![vec!["aparA".to_string(),"apare".to_string(),"aparAH".to_string(),],vec!["aparAm".to_string(),"apare".to_string(),"aparAH".to_string(),],vec!["aparayA".to_string(),"aparAByAm".to_string(),"aparABiH".to_string(),],vec!["aparasyE".to_string(),"aparAByAm".to_string(),"aparAByaH".to_string(),],vec!["aparasyAH".to_string(),"aparAByAm".to_string(),"aparAByaH".to_string(),],vec!["aparasyAH".to_string(),"aparayoH".to_string(),"aparAsAm".to_string(),],vec!["aparasyAm".to_string(),"aparayoH".to_string(),"aparAzu".to_string(),],vec!["apare".to_string(),"apare".to_string(),"aparAH".to_string(),],]);
  m.insert(("apara".to_string(),"nap".to_string()), vec![vec!["aparam".to_string(),"apare".to_string(),"aparARi".to_string(),],vec!["aparam".to_string(),"apare".to_string(),"aparARi".to_string(),],vec!["apareRa".to_string(),"aparAByAm".to_string(),"aparEH".to_string(),],vec!["aparasmE".to_string(),"aparAByAm".to_string(),"apareByaH".to_string(),],vec!["aparasmAt".to_string(),"aparAByAm".to_string(),"apareByaH".to_string(),],vec!["aparasya".to_string(),"aparayoH".to_string(),"aparezAm".to_string(),],vec!["aparasmin".to_string(),"aparayoH".to_string(),"aparezu".to_string(),],vec!["apara".to_string(),"apare".to_string(),"aparARi".to_string(),],]);
  m.insert(("anya".to_string(),"pum".to_string()), vec![vec!["anyaH".to_string(),"anyO".to_string(),"anye".to_string(),],vec!["anyam".to_string(),"anyO".to_string(),"anyAn".to_string(),],vec!["anyena".to_string(),"anyAByAm".to_string(),"anyEH".to_string(),],vec!["anyasmE".to_string(),"anyAByAm".to_string(),"anyeByaH".to_string(),],vec!["anyasmAt".to_string(),"anyAByAm".to_string(),"anyeByaH".to_string(),],vec!["anyasya".to_string(),"anyayoH".to_string(),"anyezAm".to_string(),],vec!["anyasmin".to_string(),"anyayoH".to_string(),"anyezu".to_string(),],vec!["anya".to_string(),"anyO".to_string(),"anye".to_string(),],]);
  m.insert(("anya".to_string(),"stri".to_string()), vec![vec!["anyA".to_string(),"anye".to_string(),"anyAH".to_string(),],vec!["anyAm".to_string(),"anye".to_string(),"anyAH".to_string(),],vec!["anyayA".to_string(),"anyAByAm".to_string(),"anyABiH".to_string(),],vec!["anyasyE".to_string(),"anyAByAm".to_string(),"anyAByaH".to_string(),],vec!["anyasyAH".to_string(),"anyAByAm".to_string(),"anyAByaH".to_string(),],vec!["anyasyAH".to_string(),"anyayoH".to_string(),"anyAsAm".to_string(),],vec!["anyasyAm".to_string(),"anyayoH".to_string(),"anyAzu".to_string(),],vec!["anye".to_string(),"anye".to_string(),"anyAH".to_string(),],]);
  m.insert(("anya".to_string(),"nap".to_string()), vec![vec!["anyam".to_string(),"anye".to_string(),"anyARi".to_string(),],vec!["anyam".to_string(),"anye".to_string(),"anyARi".to_string(),],vec!["anyena".to_string(),"anyAByAm".to_string(),"anyEH".to_string(),],vec!["anyasmE".to_string(),"anyAByAm".to_string(),"anyeByaH".to_string(),],vec!["anyasmAt".to_string(),"anyAByAm".to_string(),"anyeByaH".to_string(),],vec!["anyasya".to_string(),"anyayoH".to_string(),"anyezAm".to_string(),],vec!["anyasmin".to_string(),"anyayoH".to_string(),"anyezu".to_string(),],vec!["anya".to_string(),"anye".to_string(),"anyARi".to_string(),],]);
  m.insert(("paJcan".to_string(),"pum".to_string()), vec![vec!["paJcaH".to_string(),"paJcO".to_string(),"paJcaH".to_string(),],vec!["paJcam".to_string(),"paJcO".to_string(),"paJcan".to_string(),],vec!["paJcaBiH".to_string(),"paJcaByAm".to_string(),"paJcaBiH".to_string(),],vec!["paJcaByaH".to_string(),"paJcaByAm".to_string(),"paJcaByaH".to_string(),],vec!["paJcaByaH".to_string(),"paJcaByAm".to_string(),"paJcaByaH".to_string(),],vec!["paJcasya".to_string(),"paJcoH".to_string(),"paJcAnAm".to_string(),],vec!["paJcasu".to_string(),"paJcasu".to_string(),"paJcasu".to_string(),],]);
  m.insert(("paJcan".to_string(),"stri".to_string()), vec![vec!["paYcI".to_string(),"paYco".to_string(),"paYcaH".to_string(),],vec!["paYcIm".to_string(),"paYco".to_string(),"paYcaH".to_string(),],vec!["paYcIBiH".to_string(),"paYcIByAm".to_string(),"paYcIBiH".to_string(),],vec!["paYcIByaH".to_string(),"paYcIByAm".to_string(),"paYcIByaH".to_string(),],vec!["paYcIByaH".to_string(),"paYcIByAm".to_string(),"paYcIByaH".to_string(),],vec!["paYcIByaH".to_string(),"paYcoH".to_string(),"paYcInAm".to_string(),],vec!["paYcIsu".to_string(),"paYcoH".to_string(),"paYcIsu".to_string(),],]);
  m.insert(("paJcan".to_string(),"nap".to_string()), vec![vec!["paJcan".to_string(),"paJcAni".to_string(),"paJcAni".to_string(),],vec!["paJcan".to_string(),"paJcAni".to_string(),"paJcAni".to_string(),],vec!["paJcaBiH".to_string(),"paJcaByAm".to_string(),"paJcaBiH".to_string(),],vec!["paJcaByaH".to_string(),"paJcaByAm".to_string(),"paJcaByaH".to_string(),],vec!["paJcaByaH".to_string(),"paJcaByAm".to_string(),"paJcaByaH".to_string(),],vec!["paJcasya".to_string(),"paJcoH".to_string(),"paJcAnAm".to_string(),],vec!["paJcasu".to_string(),"paJcasu".to_string(),"paJcasu".to_string(),],]);
  m.insert(("zaq".to_string(),"pum".to_string()), vec![vec!["zaq".to_string(),"zaqO".to_string(),"zaq".to_string(),],vec!["zaqam".to_string(),"zaqO".to_string(),"zaws".to_string(),],vec!["zaqBiH".to_string(),"zaqByAm".to_string(),"zaqBiH".to_string(),],vec!["zaqByaH".to_string(),"zaqByAm".to_string(),"zaqByaH".to_string(),],vec!["zaqByaH".to_string(),"zaqByAm".to_string(),"zaqByaH".to_string(),],vec!["zaqasya".to_string(),"zaqNoH".to_string(),"zawsAm".to_string(),],vec!["zaqzu".to_string(),"zaqzu".to_string(),"zaqzu".to_string(),],]);
  m.insert(("zaq".to_string(),"stri".to_string()), vec![vec!["zaqI".to_string(),"zaqo".to_string(),"zaqaH".to_string(),],vec!["zaqIm".to_string(),"zaqo".to_string(),"zaqaH".to_string(),],vec!["zaqIBiH".to_string(),"zaqIByAm".to_string(),"zaqIBiH".to_string(),],vec!["zaqIByaH".to_string(),"zaqIByAm".to_string(),"zaqIByaH".to_string(),],vec!["zaqIByaH".to_string(),"zaqIByAm".to_string(),"zaqIByaH".to_string(),],vec!["zaqIByaH".to_string(),"zaqoH".to_string(),"zaqInAm".to_string(),],vec!["zaqIsu".to_string(),"zaqoH".to_string(),"zaqIsu".to_string(),],]);
  m.insert(("zaq".to_string(),"nap".to_string()), vec![vec!["zaq".to_string(),"zaqRI".to_string(),"zaqRi".to_string(),],vec!["zaq".to_string(),"zaqRI".to_string(),"zaqRi".to_string(),],vec!["zaqBiH".to_string(),"zaqByAm".to_string(),"zaqBiH".to_string(),],vec!["zaqByaH".to_string(),"zaqByAm".to_string(),"zaqByaH".to_string(),],vec!["zaqByaH".to_string(),"zaqByAm".to_string(),"zaqByaH".to_string(),],vec!["zaqasya".to_string(),"zaqNoH".to_string(),"zawsAm".to_string(),],vec!["zaqzu".to_string(),"zaqzu".to_string(),"zaqzu".to_string(),],]);
  m.insert(("saptan".to_string(),"pum".to_string()), vec![vec!["saptaH".to_string(),"saptO".to_string(),"saptaH".to_string(),],vec!["saptam".to_string(),"saptO".to_string(),"saptAn".to_string(),],vec!["saptaBiH".to_string(),"saptaByAm".to_string(),"saptaBiH".to_string(),],vec!["saptaByaH".to_string(),"saptaByAm".to_string(),"saptaByaH".to_string(),],vec!["saptaByaH".to_string(),"saptaByAm".to_string(),"saptaByaH".to_string(),],vec!["saptasya".to_string(),"saptoH".to_string(),"saptAnAm".to_string(),],vec!["saptasu".to_string(),"saptasu".to_string(),"saptasu".to_string(),],]);
  m.insert(("saptan".to_string(),"stri".to_string()), vec![vec!["saptI".to_string(),"sapto".to_string(),"saptaH".to_string(),],vec!["saptIm".to_string(),"sapto".to_string(),"saptaH".to_string(),],vec!["saptIBiH".to_string(),"saptIByAm".to_string(),"saptIBiH".to_string(),],vec!["saptIByaH".to_string(),"saptIByAm".to_string(),"saptIByaH".to_string(),],vec!["saptIByaH".to_string(),"saptIByAm".to_string(),"saptIByaH".to_string(),],vec!["saptIByaH".to_string(),"saptoH".to_string(),"saptInAm".to_string(),],vec!["saptIsu".to_string(),"saptoH".to_string(),"saptIsu".to_string(),],]);
  m.insert(("saptan".to_string(),"nap".to_string()), vec![vec!["sapta".to_string(),"saptAni".to_string(),"saptAni".to_string(),],vec!["sapta".to_string(),"saptAni".to_string(),"saptAni".to_string(),],vec!["saptaBiH".to_string(),"saptaByAm".to_string(),"saptaBiH".to_string(),],vec!["saptaByaH".to_string(),"saptaByAm".to_string(),"saptaByaH".to_string(),],vec!["saptaByaH".to_string(),"saptaByAm".to_string(),"saptaByaH".to_string(),],vec!["saptasya".to_string(),"saptoH".to_string(),"saptAnAm".to_string(),],vec!["saptasu".to_string(),"saptasu".to_string(),"saptasu".to_string(),],]);
  m.insert(("azwan".to_string(),"pum".to_string()), vec![vec!["azwaH".to_string(),"azwO".to_string(),"azwaH".to_string(),],vec!["azwam".to_string(),"azwO".to_string(),"azWAn".to_string(),],vec!["azwaBiH".to_string(),"azwaByAm".to_string(),"azwaBiH".to_string(),],vec!["azwaByaH".to_string(),"azwaByAm".to_string(),"azwaByaH".to_string(),],vec!["azwaByaH".to_string(),"azwaByAm".to_string(),"azwaByaH".to_string(),],vec!["azwasya".to_string(),"azwoH".to_string(),"azwAnAm".to_string(),],vec!["azwasu".to_string(),"azwasu".to_string(),"azwasu".to_string(),],]);
  m.insert(("azwan".to_string(),"stri".to_string()), vec![vec!["azwI".to_string(),"azwo".to_string(),"azwaH".to_string(),],vec!["azwIm".to_string(),"azwo".to_string(),"azwaH".to_string(),],vec!["azwIBiH".to_string(),"azwIByAm".to_string(),"azwIBiH".to_string(),],vec!["azwIByaH".to_string(),"azwIByAm".to_string(),"azwIByaH".to_string(),],vec!["azwIByaH".to_string(),"azwIByAm".to_string(),"azwIByaH".to_string(),],vec!["azwIByaH".to_string(),"azwoH".to_string(),"azwInAm".to_string(),],vec!["azwIsu".to_string(),"azwoH".to_string(),"azwIsu".to_string(),],]);
  m.insert(("azwan".to_string(),"nap".to_string()), vec![vec!["azwan".to_string(),"azwAni".to_string(),"azwAni".to_string(),],vec!["azwan".to_string(),"azwAni".to_string(),"azwAni".to_string(),],vec!["azwaBiH".to_string(),"azwaByAm".to_string(),"azwaBiH".to_string(),],vec!["azwaByaH".to_string(),"azwaByAm".to_string(),"azwaByaH".to_string(),],vec!["azwaByaH".to_string(),"azwaByAm".to_string(),"azwaByaH".to_string(),],vec!["azwasya".to_string(),"azwoH".to_string(),"azwAnAm".to_string(),],vec!["azwasu".to_string(),"azwasu".to_string(),"azwasu".to_string(),],]);
  m.insert(("navan".to_string(),"pum".to_string()), vec![vec!["navaH".to_string(),"navO".to_string(),"navaH".to_string(),],vec!["navam".to_string(),"navO".to_string(),"navAn".to_string(),],vec!["navaBiH".to_string(),"navaByAm".to_string(),"navaBiH".to_string(),],vec!["navaByaH".to_string(),"navaByAm".to_string(),"navaByaH".to_string(),],vec!["navaByaH".to_string(),"navaByAm".to_string(),"navaByaH".to_string(),],vec!["navasya".to_string(),"navoH".to_string(),"navAnAm".to_string(),],vec!["navasu".to_string(),"navasu".to_string(),"navasu".to_string(),],]);
  m.insert(("navan".to_string(),"stri".to_string()), vec![vec!["navI".to_string(),"navo".to_string(),"navaH".to_string(),],vec!["navIm".to_string(),"navo".to_string(),"navaH".to_string(),],vec!["navIBiH".to_string(),"navIByAm".to_string(),"navIBiH".to_string(),],vec!["navIByaH".to_string(),"navIByAm".to_string(),"navIByaH".to_string(),],vec!["navIByaH".to_string(),"navIByAm".to_string(),"navIByaH".to_string(),],vec!["navIByaH".to_string(),"navoH".to_string(),"navInAm".to_string(),],vec!["navIsu".to_string(),"navoH".to_string(),"navIsu".to_string(),],]);
  m.insert(("navan".to_string(),"nap".to_string()), vec![vec!["nava".to_string(),"navAni".to_string(),"navAni".to_string(),],vec!["nava".to_string(),"navAni".to_string(),"navAni".to_string(),],vec!["navaBiH".to_string(),"navaByAm".to_string(),"navaBiH".to_string(),],vec!["navaByaH".to_string(),"navaByAm".to_string(),"navaByaH".to_string(),],vec!["navaByaH".to_string(),"navaByAm".to_string(),"navaByaH".to_string(),],vec!["navasya".to_string(),"navoH".to_string(),"navAnAm".to_string(),],vec!["navasu".to_string(),"navasu".to_string(),"navasu".to_string(),],]);
  m.insert(("daSan".to_string(),"pum".to_string()), vec![vec!["daSaH".to_string(),"daSO".to_string(),"daSaH".to_string(),],vec!["daSam".to_string(),"daSO".to_string(),"daSAn".to_string(),],vec!["daSaBiH".to_string(),"daSaByAm".to_string(),"daSaBiH".to_string(),],vec!["daSaByaH".to_string(),"daSaByAm".to_string(),"daSaByaH".to_string(),],vec!["daSaByaH".to_string(),"daSaByAm".to_string(),"daSaByaH".to_string(),],vec!["daSasya".to_string(),"daSoH".to_string(),"daSAnAm".to_string(),],vec!["daSasu".to_string(),"daSasu".to_string(),"daSasu".to_string(),],]);
  m.insert(("daSan".to_string(),"stri".to_string()), vec![vec!["daSI".to_string(),"daSo".to_string(),"daSaH".to_string(),],vec!["daSIm".to_string(),"daSo".to_string(),"daSaH".to_string(),],vec!["daSIBiH".to_string(),"daSIByAm".to_string(),"daSIBiH".to_string(),],vec!["daSIByaH".to_string(),"daSIByAm".to_string(),"daSIByaH".to_string(),],vec!["daSIByaH".to_string(),"daSIByAm".to_string(),"daSIByaH".to_string(),],vec!["daSIByaH".to_string(),"daSoH".to_string(),"daSInAm".to_string(),],vec!["daSIsu".to_string(),"daSoH".to_string(),"daSIsu".to_string(),],]);
  m.insert(("daSan".to_string(),"nap".to_string()), vec![vec!["daSa".to_string(),"daSAni".to_string(),"daSAni".to_string(),],vec!["daSa".to_string(),"daSAni".to_string(),"daSAni".to_string(),],vec!["daSaBiH".to_string(),"daSaByAm".to_string(),"daSaBiH".to_string(),],vec!["daSaByaH".to_string(),"daSaByAm".to_string(),"daSaByaH".to_string(),],vec!["daSaByaH".to_string(),"daSaByAm".to_string(),"daSaByaH".to_string(),],vec!["daSasya".to_string(),"daSoH".to_string(),"daSAnAm".to_string(),],vec!["daSasu".to_string(),"daSasu".to_string(),"daSasu".to_string(),],]);
  m }

pub fn generate(base: &str, linga: &str) -> Option<PronounTable> {
    let linga_eff = if base=="asmad" || base=="yuzmad" || base=="ubha" || base=="am" { "any" } else { linga };
    let table = pronouns().get(&(base.to_string(), linga_eff.to_string()))?.clone();
    let vibhaktis = ["prathamA","dvitIyA","tfIyA","caturTI","paYcamI","zazWI","saptamI"];
    let mut map = HashMap::new();
    for (i, row) in table.iter().enumerate() {
        let v = vibhaktis[i].to_string();
        let forms: Vec<String> = row.iter().map(|s| s.replace(',',"/")).collect();
        map.insert(v, forms);
    }
    Some(PronounTable { base: base.to_string(), linga: linga_eff.to_string(), table: map })
}
pub fn analyze(word: &str) -> Vec<HashMap<String,String>> {
    let mut out=Vec::new();
    let vibhaktis = ["prathamA","dvitIyA","tfIyA","caturTI","paYcamI","zazWI","saptamI"];
    for ((base,linga), table) in pronouns() {
        for (vi,row) in table.iter().enumerate() {
            for (vac_idx, forms_str) in row.iter().enumerate() {
                for form in forms_str.split(',') {
                    if form==word {
                        let mut m=HashMap::new();
                        m.insert("pratipadika".to_string(), base.clone());
                        m.insert("linga".to_string(), linga.clone());
                        m.insert("vibhakti".to_string(), vibhaktis[vi].to_string());
                        m.insert("vacana".to_string(), (vac_idx+1).to_string());
                        out.push(m);
                    }
                }
            }
        }
    }
    out
}
