//! data — dhātupāṭha compact (2259 roots) + gold cross-check.
//! `dhatus_compact.rs` is generated by `build.rs` from skt-morph-data if present; otherwise committed fallback.
//! Never used as source for generate — only for dhātu lookup + test gold.
pub mod dhatus_compact;
pub use dhatus_compact::DHATUS;
